### ISSUE TITLE
lastUpdated Column removed in previous commit by mistake

### ISSUE THREAD

**Issue by idoiamurua** [eclipse-edc/DataDashboard#142]
We found a bug in https://github.com/eclipse-edc/DataDashboard/blob/main/src/modules/edc-demo/components/transfer-history/transfer-history-viewer.component.html file. We think that the "lastUpdated" column was removed by mistake from the Transfer History page in a previous commit. 
The missing column should be added as follows:
```
 <ng-container matColumnDef="lastUpdated">
            <th mat-header-cell matHeaderCellDef scope="col">Last updated</th>
            <td mat-cellmatCellDef="let item">{{asDate(item.stateTimestamp)}}</td>
 </ng-container> 
```
Otherwise, the Transfer History page of the DashBoard gives an error in the console.

**Comment by ndr-brt** [comment]
thanks for reporting, could you please provide a PR for this?

**Comment by idoiamurua** [comment]
Just created the PR https://github.com/eclipse-edc/DataDashboard/pull/148
