### ISSUE TITLE
Incompatible with v2 management endpoints

### ISSUE THREAD

**Issue by tygross025** [eclipse-edc/DataDashboard#26]
# Bug Report

## Describe the Bug
As of v0.1.0 of the EDC Connector the v1 management api endpoints were removed. The DataDashboard relies on the removed endpoins and is thus not compatible with the newest versions of the connector. 

### Expected Behavior
DataDashboard should function the same with newer versions of EDC as before. 

## Steps to Reproduce
1. Start DataDashboard with a EDC connector version >=v0.1.0
2. Observe that DataDashboard cannot retrieve information from management api

## Context Information
- Used EDC Connector v0.1.2 from the eclipse-edc/MinimumViableDataspace repository

## Possible Implementation
Many of the possible depreciated endpoints used are marked as depreciated in openapi/management-api.yaml

**Comment by Rosinski1** [comment]
Is there any plan for when to expect the update?
Because currently the [MVD](https://github.com/eclipse-edc/MinimumViableDataspace) cannot be used interactively with the dashboard, because it uses EDC connectors with the Management API `v2`.

**Comment by SebastianOpriel** [comment]
If no update is available here. Maybe its worth to have a look at our (sovity's) [Community Edition EDC](https://github.com/sovity/edc-extensions). We are currently migrating our UI to Core EDC v1.0.x: https://github.com/sovity/edc-ui

**Comment by tygross025** [comment]
Is @paullatzelsperger able to review this pull request to resolve this issue?
