### ISSUE TITLE
EDC-management: "Bad Request" when creating an asset

### ISSUE THREAD

**Issue by edwo-dev** [eclipse-edc/DataDashboard#47]
# Bug Report

## Describe the Bug

Asset can not be created. 'Bad Request' error is thrown.
Inserted information is valid and blob file exists.

### Expected Behavior

1. Creates asset

### Observed Behavior

1. Throws error message
3. Does not create asset

## Steps to Reproduce

1. Go to 'Assets'
4. Click on 'Create asset'
5. Insert asset information
6. Click 'create'
7. See error

## Context Information

- Used version [DataDashboard 2023-18-08]
- OS: [Windows/CentOS7]

## Error Information

`zone.js:2680     POST http://localhost:9191/api/management/v3/assets 400 (Bad Request)`

`{
    "headers": {
        "normalizedNames": {},
        "lazyUpdate": null
    },
    "status": 400,
    "statusText": "Bad Request",
    "url": "http://localhost:9191/api/management/v3/assets",
    "ok": false,
    "name": "HttpErrorResponse",
    "message": "Http failure response for http://localhost:9191/api/management/v3/assets: 400 Bad Request",
    "error": {
        "servlet": "EDC-management",
        "message": "Bad Request",
        "url": "/api/management/v3/assets",
        "status": "400"
    }
}`

## Detailed Description

<img width="645" alt="error-1" src="https://github.com/eclipse-edc/DataDashboard/assets/61189244/c18822f3-2f68-4518-ae2d-a91df6b94c9b">
<img width="959" alt="error-2" src="https://github.com/eclipse-edc/DataDashboard/assets/61189244/90bf3848-d012-42c5-bc21-0c30ff19d6d3">

**Comment by ndr-brt** [comment]
Thanks for reporting, yes, the current client implementation seems not to work very well, I think #38 could solve all this kind of issues quite easily

**Comment by ansenquan** [comment]
I have met the same question. This problem also occurs when creating policies and contract definitions. 
I found that the problem was caused by the request body parameters. This is the request body for now:
```  {
    "asset": {
        "properties": {
            "asset:prop:name": "1",
            "asset:prop:version": "1",
            "asset:prop:id": "1",
            "asset:prop:contenttype": ""
        }
    },
    "dataAddress": {
        "properties": {
            "type": "AzureStorage",
            "account": "1",
            "container": "src-container",
            "blobname": "1",
            "keyName": "1-key1"
        }
    }
}
```


However, when MinimumViableDataspace\deployment\data\MVD.postman_collection.json uses Newman to construct the initial two assets, the request body format is different. I tried to construct the request body in this format and found that the request received a 200 response：
``` {
    "@context": 
    {
        "edc": "https://w3id.org/edc/v0.0.1/ns/"
    },
    "edc:asset": 
    {
        "@id": "file1_company1",
        "edc:properties":
        {
            "edc:name": "file1_company1",
            "edc:contenttype": "text/plain",
            "edc:version": "1.0",
            "edc:type": "AzureStorage"
        }
    },
    "edc:dataAddress": {
        "edc:type": "AzureStorage",
        "edc:properties": {
            "edc:account": "company1assets",
            "edc:container": "src-container",
            "edc:blobname": "file1.txt",
            "edc:keyName": "company1assets-key1"
        }
    }
}
