### ISSUE TITLE
Dashboard can not fetch data offers from federated catalog

### ISSUE THREAD

**Issue by MichaelSteinert** [eclipse-edc/DataDashboard#64]
# Bug Report

## Describe the Bug

No data offers can be fetched from the federated catalog.

### Expected Behavior

All data offers from the federated catalogue should be fetched.

### Observed Behavior

The tab "Catalog Browser" remains without data offers.

## Steps to Reproduce

1. Run MVD with current EDC
2. Click on tab "Catalog Browser"

## Context Information

- Used version: EDC v0.2.1
- OS: Linux

## Detailed Description

![datadashboard](https://github.com/eclipse-edc/DataDashboard/assets/133106264/538685f2-08b5-4018-88e1-78550a7e700f)

## Possible Implementation

the called end point does not exist. The `undefineid` must be removed from the URL

**Comment by edwo-dev** [comment]
Do you use the latest commit https://github.com/eclipse-edc/DataDashboard/commit/550f6d0b557bf76b5ab7cf665d6c1a98cb156186?

Maybe you have to change the `app.config.json` files for each company from

```
{
  ...
  "dataManagementApiUrl": "http://localhost:9191/api/management",
  ...
}
```

to 
```
{
  ...
  "managementApiUrl": "http://localhost:9191/api/management",
  "catalogUrl": "http://localhost:9191/api/management",
  ...
}
```
