### ISSUE TITLE
EDC-management: "Unauthorized" when fetching "Contract Definitions"

### ISSUE THREAD

**Issue by edwo-dev** [eclipse-edc/DataDashboard#87]
# Bug Report

## Describe the Bug

`Contract definitions` can not be fetched.
HTTP Error 401 is thrown (Unauthorized).

### Expected Behavior

Contract Definitions are fetched and list of items is shown.

### Observed Behavior

1. Throws error message
2. Does not fetch and show items

## Steps to Reproduce

1. Go to 'Contract Definitions'
5. See error

## Context Information

- Used version
  - [DataDashboard https://github.com/eclipse-edc/DataDashboard/commit/dc4f57d3492706d39a6f7f663e706a52ca073efb]
  - [EDC v0.2.0]
- OS: [Windows/CentOS7]

## Error Information

<img width="960" alt="ContractDefinitionsError" src="https://github.com/eclipse-edc/DataDashboard/assets/61189244/839b1777-34ad-4492-aad1-a1ee9f4c8513">

## Detailed Description

Response:

```
[
    {
        "message": "Request could not be authenticated",
        "type": "AuthenticationFailed",
        "path": null,
        "invalidValue": null
    }
]
```

**Comment by ndr-brt** [comment]
Could you look at the request headers? Is there the api token one? What is the content eventually?

**Comment by edwo-dev** [comment]
These are the request headers:

```
Accept: */*
Accept-Encoding: gzip, deflate, br
Accept-Language: de-DE,de;q=0.9,en-US;q=0.8,en;q=0.7
Cache-Control: no-cache
Connection: keep-alive
Content-Length: 0
Content-Type: application/json
Host: localhost:9192
Origin: http://localhost:7081
Pragma: no-cache
Referer: http://localhost:7081/
Sec-Ch-Ua: "Chromium";v="116", "Not)A;Brand";v="24", "Google Chrome";v="116"
Sec-Ch-Ua-Mobile: ?0
Sec-Ch-Ua-Platform: "Windows"
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-site
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36
X-Api-Key:
```

`X-Api-Key' is missing!
