### ISSUE TITLE
Newly created 'Contract Definition' is not reflected in 'Catalog Browser'

### ISSUE THREAD

**Issue by edwo-dev** [eclipse-edc/DataDashboard#92]
# Bug Report

## Describe the Bug

When a new `contract definiton` is created on "Contract Definitions" page, it does not appear in the "Catalog Browser"

### Expected Behavior

When a new contract definition is created it has to appear in the Catalog Browser.

## Steps to Reproduce

1. Go to 'Contract Definitions'
2. Click on 'Create contract definition'
3. Insert required properties
4. Click on 'Create'
5. See new item in list
6. Go to 'Catalog Browser'
8. See missing contract

## Context Information

_Add any other context about the problem here._

- Used version
  - [DataDashboard #8c178ad]
  - [EDC v0.2.0]
- OS: [Windows/CentOS7]

## Detailed Description

![Contract-Definitions](https://github.com/eclipse-edc/DataDashboard/assets/61189244/46bf5d84-b4d7-4fb4-b970-e669701ea188)
![Catalog-Browser (1)](https://github.com/eclipse-edc/DataDashboard/assets/61189244/9816afa8-4add-43da-a2cd-6e9b22cf8f7e)

**Comment by ndr-brt** [comment]
Likely will be fixed by #54

**Comment by janpmeyer** [comment]
The leftOperand of the AssetSelector has the wrong value.

Thats why a Asset is not mapped by a Contract Definition.
